from fpdf import FPDF
import tempfile

class StatIQReport(FPDF):
    def header(self):
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(0, 51, 102)
        self.cell(0, 10, "StatIQ - Bank Statement Analysis Report", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(120, 120, 120)
        self.cell(0, 6, "Automated Credit Analysis for NBFCs, CA Firms and DSAs", align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(3)
        self.set_draw_color(0, 51, 102)
        self.set_line_width(0.5)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(4)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Generated by StatIQ | Page {self.page_no()}", align="C")


def clean_text(text):
    """Remove characters unsupported by Helvetica."""
    replacements = {
        "\u2014": "-", "\u2013": "-", "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"', "\u20b9": "Rs.", "\u2022": "*",
        "\u2026": "...", "\u00a0": " "
    }
    for char, replacement in replacements.items():
        text = text.replace(char, replacement)
    return text.encode("latin-1", errors="replace").decode("latin-1")


def generate_pdf_report(account_holder, analytics, anomaly_df, ai_report):
    pdf = StatIQReport()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Account Info
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(0, 51, 102)
    pdf.cell(0, 8, "Account Information", new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(0, 51, 102)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 7, f"Account Holder: {account_holder}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # KPI Metrics
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(0, 51, 102)
    pdf.cell(0, 8, "Financial Metrics", new_x="LMARGIN", new_y="NEXT")
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)

    metrics = [
        ("Total Credits", f"Rs. {analytics['total_credits']:,.2f}"),
        ("Total Debits", f"Rs. {analytics['total_debits']:,.2f}"),
        ("Salary Credits", f"Rs. {analytics['salary_credits']:,.2f}"),
        ("EMI Payments", f"Rs. {analytics['emi_payments']:,.2f}"),
        ("EMI Obligation Ratio", f"{analytics['emi_ratio']}%"),
        ("Average Monthly Balance", f"Rs. {analytics['avg_monthly_balance']:,.2f}"),
        ("Bounce Count", str(analytics['bounce_count'])),
    ]

    for label, value in metrics:
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(0, 0, 0)
        pdf.cell(80, 7, label + ":", new_x="END", new_y="LAST")
        pdf.set_font("Helvetica", "", 10)
        pdf.cell(0, 7, value, new_x="LMARGIN", new_y="NEXT")
    pdf.ln(3)

    # Risk Flags
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(0, 51, 102)
    pdf.cell(0, 8, "Risk Flags", new_x="LMARGIN", new_y="NEXT")
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)

    pdf.set_font("Helvetica", "", 10)
    if anomaly_df.empty:
        pdf.set_text_color(0, 0, 0)
        pdf.cell(0, 7, "No anomalies detected.", new_x="LMARGIN", new_y="NEXT")
    else:
        for _, row in anomaly_df.iterrows():
            pdf.set_text_color(180, 0, 0)
            line = f"[{row['Flag']}] {clean_text(str(row['Narration']))} - Amount: {row['Amount']}"
            pdf.cell(0, 7, line, new_x="LMARGIN", new_y="NEXT")
    pdf.set_text_color(0, 0, 0)
    pdf.ln(3)

    # AI Report
    pdf.set_font("Helvetica", "B", 11)
    pdf.set_text_color(0, 51, 102)
    pdf.cell(0, 8, "AI Creditworthiness Assessment", new_x="LMARGIN", new_y="NEXT")
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(0, 0, 0)
    pdf.multi_cell(0, 6, clean_text(ai_report))

    tmp = tempfile.NamedTemporaryFile(delete=False, suffix=".pdf")
    pdf.output(tmp.name)
    return tmp.name